apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-nginx
spec:
  project: default
  source:
    repoURL: 'https://github.com/Erwinathor/argocd-demo'
    targetRevision: HEAD
    path: applications/nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
syncPolicy:
  automated:
    prune: false
    selfHeal: false