apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-nginx
spec:
  project: default
  source:
    repoURL: https://github.com/Erwinathor/argocd-demo.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default